# Generated by Django 4.2.27 on 2026-02-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('slack', 'Slack'), ('mailing_list', 'Mailing list'), ('wg21', 'WG21')], db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'cppa_user_tracker_baseprofile',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
                'db_table': 'cppa_user_tracker_identity',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TmpIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temporary identity',
                'verbose_name_plural': 'Temporary identities',
                'db_table': 'cppa_user_tracker_tmpidentity',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cppa_user_tracker.baseprofile')),
                ('github_account_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=512)),
                ('account_type', models.CharField(choices=[('user', 'User'), ('organization', 'Organization'), ('enterprise', 'Enterprise')], db_column='account_type', db_index=True, default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cppa_user_tracker_githubaccount',
            },
            bases=('cppa_user_tracker.baseprofile',),
        ),
        migrations.CreateModel(
            name='MailingListProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cppa_user_tracker.baseprofile')),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cppa_user_tracker_mailinglistprofile',
            },
            bases=('cppa_user_tracker.baseprofile',),
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cppa_user_tracker.baseprofile')),
                ('slack_user_id', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cppa_user_tracker_slackuser',
            },
            bases=('cppa_user_tracker.baseprofile',),
        ),
        migrations.CreateModel(
            name='WG21PaperAuthorProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cppa_user_tracker.baseprofile')),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cppa_user_tracker_wg21paperauthorprofile',
            },
            bases=('cppa_user_tracker.baseprofile',),
        ),
        migrations.CreateModel(
            name='TempProfilieIdentityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_profile', models.ForeignKey(db_column='base_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='temp_identity_relations', to='cppa_user_tracker.baseprofile')),
                ('target_identity', models.ForeignKey(db_column='target_identity_id', on_delete=django.db.models.deletion.CASCADE, related_name='temp_profile_relations', to='cppa_user_tracker.tmpidentity')),
            ],
            options={
                'verbose_name': 'Temporary profile-identity relation',
                'verbose_name_plural': 'Temporary profile-identity relations',
                'db_table': 'cppa_user_tracker_tempprofilieidentityrelation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_profile', models.ForeignKey(db_column='base_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cppa_user_tracker.baseprofile')),
            ],
            options={
                'db_table': 'cppa_user_tracker_email',
            },
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='identity',
            field=models.ForeignKey(blank=True, db_column='identity_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='cppa_user_tracker.identity'),
        ),
    ]
