# Generated by Django 4.2.28 on 2026-02-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_user_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempProfilieIdentityRelation',
            new_name='TempProfileIdentityRelation',
        ),
        migrations.AlterModelTable(
            name='tempprofileidentityrelation',
            table='cppa_user_tracker_tempprofileidentityrelation',
        ),
    ]
