# Generated by Django 4.2.28 on 2026-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_user_tracker', '0003_discordprofile_alter_baseprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='slack_user_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterModelTable(
            name='baseprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discordprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='email',
            table=None,
        ),
        migrations.AlterModelTable(
            name='githubaccount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='identity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mailinglistprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='slackuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tempprofileidentityrelation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tmpidentity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wg21paperauthorprofile',
            table=None,
        ),
    ]
