# Generated by Django 4.2.28 on 2026-02-24 22:01

from django.db import migrations, models
from django.db.models import Count


def pre_migrate_dedupe_slack_user_ids(apps, schema_editor):
    """
    Remove duplicate SlackUser rows per slack_user_id so the UNIQUE constraint
    can be applied. Keeps the first row per slack_user_id; reassigns FKs
    (Email, and cppa_slack_tracker SlackChannelMembership /
    SlackChannelMembershipChangeLog) to that canonical user, then deletes
    duplicate SlackUser and BaseProfile rows. Runs inside a transaction.
    """
    SlackUser = apps.get_model("cppa_user_tracker", "SlackUser")
    BaseProfile = apps.get_model("cppa_user_tracker", "BaseProfile")
    Email = apps.get_model("cppa_user_tracker", "Email")
    duplicates = (
        SlackUser.objects.values("slack_user_id")
        .annotate(n=Count("pk"))
        .filter(n__gt=1)
    )
    for row in duplicates:
        user_id = row["slack_user_id"]
        users = list(SlackUser.objects.filter(slack_user_id=user_id).order_by("pk"))
        if len(users) <= 1:
            continue
        canonical = users[0]
        duplicate_pks = [u.pk for u in users[1:]]
        Email.objects.filter(base_profile_id__in=duplicate_pks).update(
            base_profile_id=canonical.pk
        )
        SlackChannelMembership = apps.get_model(
            "cppa_slack_tracker", "SlackChannelMembership"
        )
        SlackChannelMembershipChangeLog = apps.get_model(
            "cppa_slack_tracker", "SlackChannelMembershipChangeLog"
        )
        if SlackChannelMembership is not None:
            SlackChannelMembership.objects.filter(user_id__in=duplicate_pks).update(
                user_id=canonical.pk
            )
        if SlackChannelMembershipChangeLog is not None:
            SlackChannelMembershipChangeLog.objects.filter(
                user_id__in=duplicate_pks
            ).update(user_id=canonical.pk)
        SlackUser.objects.filter(pk__in=duplicate_pks).delete()
        BaseProfile.objects.filter(pk__in=duplicate_pks).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_user_tracker', '0003_discordprofile_alter_baseprofile_type'),
        ('cppa_slack_tracker', '0003_alter_slackchannel_unique_team_channel_id'),
    ]

    operations = [
        migrations.RunPython(pre_migrate_dedupe_slack_user_ids, noop),
        migrations.AlterField(
            model_name='slackuser',
            name='slack_user_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterModelTable(
            name='baseprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discordprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='email',
            table=None,
        ),
        migrations.AlterModelTable(
            name='githubaccount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='identity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mailinglistprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='slackuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tempprofileidentityrelation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tmpidentity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wg21paperauthorprofile',
            table=None,
        ),
    ]
