# Generated by Django 4.2.28 on 2026-02-24 21:08

from django.db import migrations, models
from django.db.models import Count


def dedupe_slackuser_slack_user_id(apps, schema_editor):
    """Keep one SlackUser per slack_user_id; reassign Email FKs and delete duplicate SlackUsers."""
    SlackUser = apps.get_model("cppa_user_tracker", "SlackUser")
    BaseProfile = apps.get_model("cppa_user_tracker", "BaseProfile")
    Email = apps.get_model("cppa_user_tracker", "Email")
    duplicates = (
        SlackUser.objects.values("slack_user_id")
        .annotate(n=Count("pk"))
        .filter(n__gt=1)
    )
    for row in duplicates:
        user_id = row["slack_user_id"]
        users = list(SlackUser.objects.filter(slack_user_id=user_id).order_by("pk"))
        if len(users) <= 1:
            continue
        canonical = users[0]
        duplicate_pks = [u.pk for u in users[1:]]
        Email.objects.filter(base_profile_id__in=duplicate_pks).update(
            base_profile_id=canonical.pk
        )
        SlackUser.objects.filter(pk__in=duplicate_pks).delete()
        BaseProfile.objects.filter(pk__in=duplicate_pks).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_user_tracker', '0003_discordprofile_alter_baseprofile_type'),
    ]

    operations = [
        migrations.RunPython(dedupe_slackuser_slack_user_id, noop),
        migrations.AlterField(
            model_name='slackuser',
            name='slack_user_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterModelTable(
            name='baseprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discordprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='email',
            table=None,
        ),
        migrations.AlterModelTable(
            name='githubaccount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='identity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mailinglistprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='slackuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tempprofileidentityrelation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tmpidentity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wg21paperauthorprofile',
            table=None,
        ),
    ]
