# Generated by Django 4.2.28 on 2026-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_user_tracker', '0004_alter_slackuser_slack_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='slack_user_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
