# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cppa_user_tracker", "0004_alter_slackuser_slack_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wg21paperauthorprofile",
            name="author_alias",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
