# Generated by Django 4.2.27 on 2026-02-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cppa_user_tracker', '0001_initial'),
        ('github_activity_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'boost_library_tracker_boostlibrary',
                'ordering': ['repo', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoostLibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Boost library categories',
                'db_table': 'boost_library_tracker_boostlibrarycategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoostLibraryRepository',
            fields=[
                ('githubrepository_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='github_activity_tracker.githubrepository')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boost_library_tracker_boostlibraryrepository',
                'ordering': ['repo_name'],
            },
            bases=('github_activity_tracker.githubrepository',),
        ),
        migrations.CreateModel(
            name='BoostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=64, unique=True)),
                ('version_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'boost_library_tracker_boostversion',
                'ordering': ['-version_created_at', 'version'],
            },
        ),
        migrations.CreateModel(
            name='DependencyChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_add', models.BooleanField()),
                ('created_at', models.DateField(db_index=True)),
                ('client_library', models.ForeignKey(db_column='client_library_id', on_delete=django.db.models.deletion.CASCADE, related_name='dependency_changelog_as_client', to='boost_library_tracker.boostlibrary')),
                ('dep_library', models.ForeignKey(db_column='dep_library_id', on_delete=django.db.models.deletion.CASCADE, related_name='dependency_changelog_as_dep', to='boost_library_tracker.boostlibrary')),
            ],
            options={
                'db_table': 'boost_library_tracker_dependencychangelog',
                'ordering': ['-created_at', 'client_library', 'dep_library'],
            },
        ),
        migrations.CreateModel(
            name='BoostLibraryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpp_version', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(db_column='library_id', on_delete=django.db.models.deletion.CASCADE, related_name='library_versions', to='boost_library_tracker.boostlibrary')),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='library_versions', to='boost_library_tracker.boostversion')),
            ],
            options={
                'db_table': 'boost_library_tracker_boostlibraryversion',
                'ordering': ['library', 'version'],
            },
        ),
        migrations.CreateModel(
            name='BoostLibraryRoleRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintainer', models.BooleanField(default=False)),
                ('is_author', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='boost_library_roles', to='cppa_user_tracker.githubaccount')),
                ('library_version', models.ForeignKey(db_column='library_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_relationships', to='boost_library_tracker.boostlibraryversion')),
            ],
            options={
                'db_table': 'boost_library_tracker_boostlibraryrolerelationship',
                'ordering': ['library_version', 'account'],
            },
        ),
        migrations.CreateModel(
            name='BoostLibraryCategoryRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='library_relationships', to='boost_library_tracker.boostlibrarycategory')),
                ('library', models.ForeignKey(db_column='library_id', on_delete=django.db.models.deletion.CASCADE, related_name='category_relationships', to='boost_library_tracker.boostlibrary')),
            ],
            options={
                'db_table': 'boost_library_tracker_boostlibrarycategoryrelationship',
                'ordering': ['library', 'category'],
            },
        ),
        migrations.AddField(
            model_name='boostlibrary',
            name='repo',
            field=models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='boost_library_tracker.boostlibraryrepository'),
        ),
        migrations.CreateModel(
            name='BoostFile',
            fields=[
                ('github_file', models.OneToOneField(db_column='github_file_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='boost_file', serialize=False, to='github_activity_tracker.githubfile')),
                ('library', models.ForeignKey(db_column='library_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='boost_library_tracker.boostlibrary')),
            ],
            options={
                'db_table': 'boost_library_tracker_boostfile',
            },
        ),
        migrations.CreateModel(
            name='BoostDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_library', models.ForeignKey(db_column='client_library_id', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_as_client', to='boost_library_tracker.boostlibrary')),
                ('dep_library', models.ForeignKey(db_column='dep_library_id', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_as_dep', to='boost_library_tracker.boostlibrary')),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='boost_library_tracker.boostversion')),
            ],
            options={
                'db_table': 'boost_library_tracker_boostdependency',
                'ordering': ['client_library', 'version', 'dep_library'],
            },
        ),
        migrations.AddConstraint(
            model_name='dependencychangelog',
            constraint=models.UniqueConstraint(fields=('client_library', 'dep_library', 'created_at'), name='boost_library_tracker_changelog_uniq'),
        ),
        migrations.AddConstraint(
            model_name='boostlibraryversion',
            constraint=models.UniqueConstraint(fields=('library', 'version'), name='boost_library_tracker_lib_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='boostlibraryrolerelationship',
            constraint=models.UniqueConstraint(fields=('library_version', 'account'), name='boost_library_tracker_role_uniq'),
        ),
        migrations.AddConstraint(
            model_name='boostlibrarycategoryrelationship',
            constraint=models.UniqueConstraint(fields=('library', 'category'), name='boost_library_tracker_lib_cat_uniq'),
        ),
        migrations.AddConstraint(
            model_name='boostlibrary',
            constraint=models.UniqueConstraint(fields=('repo', 'name'), name='boost_library_tracker_repo_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='boostdependency',
            constraint=models.UniqueConstraint(fields=('client_library', 'version', 'dep_library'), name='boost_library_tracker_dep_uniq'),
        ),
    ]
