# Generated by Django 4.2.29 on 2026-04-08 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cppa_user_tracker", "0007_youtubespeaker_external_id"),
        ("cppa_slack_tracker", "0003_alter_slackchannel_unique_team_channel_id"),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS slack_private;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='slackteam',
            name='team_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SlackChannelPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=50)),
                ('channel_name', models.CharField(db_index=True, max_length=255)),
                ('channel_type', models.CharField(choices=[('private_channel', 'Private channel'), ('mpim', 'Multi-party direct message'), ('im', 'Direct message')], db_index=True, help_text='Type: private_channel, mpim, or im (not public_channel).', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, db_column='creator_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_private_channels', to='cppa_user_tracker.slackuser')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='private_channels', to='cppa_slack_tracker.slackteam')),
            ],
            options={
                'verbose_name': 'Slack Channel (non-public)',
                'verbose_name_plural': 'Slack Channels (non-public)',
                'db_table': 'slack_private"."cppa_slack_tracker_slackchannel_private',
            },
        ),
        migrations.CreateModel(
            name='SlackChannelMembershipPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_restricted', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cppa_slack_tracker.slackchannelprivate')),
                ('user', models.ForeignKey(db_column='slack_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='private_channel_memberships', to='cppa_user_tracker.slackuser')),
            ],
            options={
                'verbose_name': 'Slack Channel Membership (non-public)',
                'verbose_name_plural': 'Slack Channel Memberships (non-public)',
                'db_table': 'slack_private"."cppa_slack_tracker_slackchannelmembership_private',
            },
        ),
        migrations.CreateModel(
            name='SlackChannelMembershipChangeLogPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_joined', models.BooleanField(help_text='True if joined, False if left')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_changes', to='cppa_slack_tracker.slackchannelprivate')),
                ('user', models.ForeignKey(db_column='slack_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='private_membership_changes', to='cppa_user_tracker.slackuser')),
            ],
            options={
                'verbose_name': 'Slack Channel Membership Change Log (non-public)',
                'verbose_name_plural': 'Slack Channel Membership Change Logs (non-public)',
                'db_table': 'slack_private"."cppa_slack_tracker_slackchannelmembershipchangelog_private',
            },
        ),
        migrations.CreateModel(
            name='SlackMessagePrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(db_index=True, help_text='Slack message timestamp (unique per channel)', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('thread_ts', models.CharField(blank=True, db_index=True, help_text='Thread timestamp if this is a threaded message', max_length=50, null=True)),
                ('slack_message_created_at', models.DateTimeField(db_index=True)),
                ('slack_message_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cppa_slack_tracker.slackchannelprivate')),
                ('user', models.ForeignKey(blank=True, db_column='slack_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_slack_messages', to='cppa_user_tracker.slackuser')),
            ],
            options={
                'verbose_name': 'Slack Message (non-public channel)',
                'verbose_name_plural': 'Slack Messages (non-public channels)',
                'db_table': 'slack_private"."cppa_slack_tracker_slackmessage_private',
                'unique_together': {('channel', 'ts')},
            },
        ),
        migrations.AddConstraint(
            model_name='slackchannelprivate',
            constraint=models.UniqueConstraint(fields=('team', 'channel_id'), name='unique_team_channel_id_private'),
        ),
        migrations.AlterUniqueTogether(
            name='slackchannelmembershipprivate',
            unique_together={('channel', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='slackchannelmembershipchangelogprivate',
            unique_together={('channel', 'user', 'created_at')},
        ),
    ]
