# Generated by Django 4.2.29 on 2026-04-06 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_user_tracker', '0005_alter_slackuser_slack_user_id'),
        ('cppa_slack_tracker', '0003_alter_slackchannel_unique_team_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackteam',
            name='team_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SlackChannelPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=50)),
                ('channel_name', models.CharField(db_index=True, max_length=255)),
                ('channel_type', models.CharField(choices=[('private_channel', 'Private channel'), ('mpim', 'Multi-party direct message'), ('im', 'Direct message')], db_index=True, help_text='Type: private_channel, mpim, or im (not public_channel).', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, db_column='creator_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_private_channels', to='cppa_user_tracker.slackuser')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='private_channels', to='cppa_slack_tracker.slackteam')),
            ],
            options={
                'verbose_name': 'Slack Channel (non-public)',
                'verbose_name_plural': 'Slack Channels (non-public)',
                'db_table': 'cppa_slack_tracker_slackchannel_private',
            },
        ),
        migrations.AddConstraint(
            model_name='slackchannelprivate',
            constraint=models.UniqueConstraint(fields=('team', 'channel_id'), name='unique_team_channel_id_private'),
        ),
    ]
