# Generated by Django 4.2.27 on 2026-02-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cppa_user_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(db_index=True, max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('commit_at', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='cppa_user_tracker.githubaccount')),
            ],
            options={
                'db_table': 'github_activity_tracker_gitcommit',
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(db_index=True, max_length=255)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('repo_pushed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repo_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repo_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'github_activity_tracker_githubrepository',
                'ordering': ['owner_account', 'repo_name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.IntegerField(db_index=True)),
                ('issue_id', models.BigIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, max_length=20)),
                ('state_reason', models.CharField(blank=True, choices=[('completed', 'Completed'), ('not_planned', 'Not planned'), ('reopened', 'Reopened'), ('null', 'Null')], max_length=20)),
                ('issue_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('issue_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('issue_closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to='cppa_user_tracker.githubaccount')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_issues', to='cppa_user_tracker.githubaccount')),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='github_activity_tracker.githubrepository')),
            ],
            options={
                'db_table': 'github_activity_tracker_issue',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'github_activity_tracker_language',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('spdx_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('url', models.URLField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'github_activity_tracker_license',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField(db_index=True)),
                ('pr_id', models.BigIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], db_index=True, max_length=20)),
                ('head_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('base_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('pr_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pr_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pr_merged_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pr_closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_pull_requests', to='cppa_user_tracker.githubaccount')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_pull_requests', to='cppa_user_tracker.githubaccount')),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github_activity_tracker.githubrepository')),
            ],
            options={
                'db_table': 'github_activity_tracker_pullrequest',
            },
        ),
        migrations.CreateModel(
            name='RepoLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, related_name='repo_languages', to='github_activity_tracker.language')),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, related_name='repo_languages', to='github_activity_tracker.githubrepository')),
            ],
            options={
                'db_table': 'github_activity_tracker_repolanguage',
            },
        ),
        migrations.CreateModel(
            name='PullRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_review_id', models.BigIntegerField(db_index=True, unique=True)),
                ('body', models.TextField(blank=True)),
                ('in_reply_to_id', models.BigIntegerField(blank=True, null=True)),
                ('pr_review_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pr_review_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='pr_reviews', to='cppa_user_tracker.githubaccount')),
                ('pr', models.ForeignKey(db_column='pr_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='github_activity_tracker.pullrequest')),
            ],
            options={
                'db_table': 'github_activity_tracker_pullrequestreview',
            },
        ),
        migrations.CreateModel(
            name='PullRequestLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pr', models.ForeignKey(db_column='pr_id', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='github_activity_tracker.pullrequest')),
            ],
            options={
                'db_table': 'github_activity_tracker_pullrequestlabel',
            },
        ),
        migrations.CreateModel(
            name='PullRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_comment_id', models.BigIntegerField(db_index=True, unique=True)),
                ('body', models.TextField(blank=True)),
                ('pr_comment_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pr_comment_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='pr_comments', to='cppa_user_tracker.githubaccount')),
                ('pr', models.ForeignKey(db_column='pr_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='github_activity_tracker.pullrequest')),
            ],
            options={
                'db_table': 'github_activity_tracker_pullrequestcomment',
            },
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(db_column='issue_id', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='github_activity_tracker.issue')),
            ],
            options={
                'db_table': 'github_activity_tracker_issuelabel',
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_comment_id', models.BigIntegerField(db_index=True, unique=True)),
                ('body', models.TextField(blank=True)),
                ('issue_comment_created_at', models.DateTimeField(blank=True, null=True)),
                ('issue_comment_updated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='issue_comments', to='cppa_user_tracker.githubaccount')),
                ('issue', models.ForeignKey(db_column='issue_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='github_activity_tracker.issue')),
            ],
            options={
                'db_table': 'github_activity_tracker_issuecomment',
            },
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='repos', through='github_activity_tracker.RepoLanguage', to='github_activity_tracker.language'),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='licenses',
            field=models.ManyToManyField(blank=True, related_name='repos', to='github_activity_tracker.license'),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='owner_account',
            field=models.ForeignKey(db_column='owner_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='cppa_user_tracker.githubaccount'),
        ),
        migrations.CreateModel(
            name='GitHubFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(db_index=True, max_length=1024)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='github_activity_tracker.githubrepository')),
            ],
            options={
                'db_table': 'github_activity_tracker_githubfile',
                'ordering': ['repo', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='GitCommitFileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('removed', 'Removed'), ('renamed', 'Renamed'), ('copied', 'Copied'), ('changed', 'Changed')], db_index=True, max_length=20)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('patch', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(db_column='commit_id', on_delete=django.db.models.deletion.CASCADE, related_name='file_changes', to='github_activity_tracker.gitcommit')),
                ('github_file', models.ForeignKey(db_column='github_file_id', on_delete=django.db.models.deletion.CASCADE, related_name='commit_changes', to='github_activity_tracker.githubfile')),
            ],
            options={
                'db_table': 'github_activity_tracker_gitcommitfilechange',
            },
        ),
        migrations.AddField(
            model_name='gitcommit',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='commits', through='github_activity_tracker.GitCommitFileChange', to='github_activity_tracker.githubfile'),
        ),
        migrations.AddField(
            model_name='gitcommit',
            name='repo',
            field=models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github_activity_tracker.githubrepository'),
        ),
        migrations.AddConstraint(
            model_name='repolanguage',
            constraint=models.UniqueConstraint(fields=('repo', 'language'), name='github_activity_tracker_repo_lang_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pullrequestlabel',
            constraint=models.UniqueConstraint(fields=('pr', 'label_name'), name='github_activity_tracker_pr_label_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('repo', 'pr_number'), name='github_activity_tracker_repo_pr_num_uniq'),
        ),
        migrations.AddConstraint(
            model_name='issuelabel',
            constraint=models.UniqueConstraint(fields=('issue', 'label_name'), name='github_activity_tracker_issue_label_uniq'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('repo', 'issue_number'), name='github_activity_tracker_repo_issue_num_uniq'),
        ),
        migrations.AddConstraint(
            model_name='githubrepository',
            constraint=models.UniqueConstraint(fields=('owner_account', 'repo_name'), name='github_activity_tracker_repo_owner_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gitcommitfilechange',
            constraint=models.UniqueConstraint(fields=('commit', 'github_file'), name='github_activity_tracker_commit_file_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gitcommit',
            constraint=models.UniqueConstraint(fields=('repo', 'commit_hash'), name='github_activity_tracker_repo_commit_uniq'),
        ),
    ]
